### ISSUE TITLE
Sprawdzanie, czy podane słowa się rymują

### ISSUE THREAD

**Issue by bastyje** [jakublaba/pantadeusz#6]

**Comment by legeof008** [comment]
Na razie dla uproszczenia dokonałem podziału na zgłoski per ostatnia samogłoska do następnej.
To gwarantuje wykrywanie rymów męskich i żeńskich dokładnych, podobnie brzmiące litery nie są wykrywane jako rym.

**Comment by patrykferenc** [comment]
TODO: Refakoryzacja / zmiana podejścia do wykrywania rymów. Trafniejsze wykrywanie (nawet kosztem ograniczenia się do bardziej znanych rodzajów)
