### ISSUE TITLE
Ile (w całym tekście/w danej księdze/w danej strofie) znajduje się poszczególnych rodzajów rymów

### ISSUE THREAD

**Issue by bastyje** [jakublaba/pantadeusz#7]

**Comment by patrykferenc** [comment]
- [ ]  w całej książce
- [ ]  w danej księdze
- [ ]  w danej strofie (opcjonalnie, wybór przez notebook)
- [ ]  w znanych fragmentach - inwokacja, gra na rogu itp. (opcjonalnie)
